<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <AssemblyName>BetterTriggers.CLI</AssemblyName>
    <RootNamespace>BetterTriggers.CLI</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0-beta4.22272.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BetterTriggers\BetterTriggers.csproj" />
  </ItemGroup>

</Project>
